### PR TITLE
Using a DXEnvironment structure

### PR DESCRIPTION
**Pull request by orodeh**
Using a structure equivalent to `DXEnvironment` from the dxjava package. It is a structure that encapsulates the various configuration options that the dx-toolkit has.

### CODE REVIEW

**Comment by orodeh** [comment]
I unintentionally removed support for `DX_API_SERVER` environment variable (https://github.com/dnanexus/dxda/blob/aedb3fa72cdec5ade4681a352e0bc065b371e5b8/dxda.go#L234). Do we need to retain support for it? Is the old `DX_APISERVER_HOST` sufficient?

**Comment by geetduggal** [comment]
> DX_API_SERVER

It's perfectly fine to remove this in favor of the more canonical  since it was used mostly for testing on staging and we don't advertise users to use different API servers.

**Comment by orodeh** [comment]
@geetduggal, this is now good to merge. Let's do this, so I can complete the new release of dxWDL.

**Comment by orodeh** [comment]
@geetduggal, the code passed the large dxWDL tests. Please make a new dxda release when you get a chance.

**Pull request merged**
